import { AppSidebar } from "@/components/layout/SidebarAdmin";
import AdminNavbar from "@/components/layout/NavbarAdmin";
import { Toaster } from "sonner";

export const metadata = {
  title: "Dashboard HUMIC | Admin",
  description: "Generated by create Humic Website",
};

export default function AdminLayout({ children }) {
  return (
    <div className="flex min-h-screen w-screen overflow-x-hidden bg-gray-50 dark:bg-[#101010]">
      <div className="w-[240px] hidden md:block fixed inset-y-0 left-0 z-50 border-r bg-background">
        <AppSidebar />
      </div>

      <div className="flex flex-col flex-1 w-full md:ml-[240px] transition-all">
        <div className="fixed top-0 left-0 right-0 z-40 bg-background border-b border-gray-200 dark:border-white/10">
          <AdminNavbar />
        </div>
        <main className="flex-1 px-4 py-4 md:px-8 lg:px-12 overflow-y-auto pt-16 md:pt-20">
          <div className="w-full overflow-x-auto">{children}</div>
        </main>
      </div>

      <Toaster position="top-right" />
    </div>
  );
}
